services:
  hhvm:
    platform: linux/amd64
    build:
      context: ./hhvm
      dockerfile: Dockerfile
    volumes:
      - ./hhvm:/var/www

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./hhvm:/var/www
    depends_on:
      - hhvm
