version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./transcribe:/var/www/transcribe
      - ./videodata:/var/www/videodata

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8.0
    container_name: insightgao-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: insightgao
      MYSQL_USER: insight
      MYSQL_PASSWORD: insight123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
